name: nakama-node-1
data_dir: './data/'

logger:
  stdout: false
  level: 'info'
  file: '/nakama/data/logfile.log'

console:
  port: 7351
  max_message_size_bytes: 409600
  username: NK_CONSOLE_PROD_USERNAME
  password: NK_CONSOLE_PROD_PWD

runtime:
  js_entrypoint: 'build/index.js'
  js_max_count: 128
socket:
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072
matchmaker:
  interval_sec: 3
